import AnimationClipSelectInput from '../components/AnimationClipSelectInput'

export default {
  name: 'scene',
  title: '3D Scene Settings',
  type: 'document',
  fields: [
    { name: 'title', type: 'string', title: 'Scene Name' },
    {
      name: 'showStatueIndicators',
      type: 'boolean',
      title: 'Show Statue Indicators in Play Mode',
      initialValue: false,
      description: 'When enabled, shows directional indicators for section statues in the 3D Play Mode.',
    },
    {
      name: 'renderStyle',
      type: 'string',
      title: '3D Render Style',
      initialValue: 'cel',
      options: {
        list: [
          { title: 'Cel-Shaded (Toon)', value: 'cel' },
          { title: 'PBR (Physically Based)', value: 'pbr' },
        ],
      },
      description: 'Cel-shaded gives a stylized toon look; PBR gives realistic materials.',
    },
    { 
      name: 'environmentMap', 
      type: 'string', 
      title: 'Atmospheric Preset',
      options: {
        list: [
          { title: 'Cyber City (High Contrast)', value: 'city' },
          { title: 'Neon Night (Moody)', value: 'night' },
          { title: 'Digital Dawn (Bright)', value: 'apartment' },
          { title: 'Industrial Core (Metallic)', value: 'warehouse' },
          { title: 'Deep Space (Dark)', value: 'sunset' },
          { title: 'Arctic Simulation (Clean)', value: 'park' },
          { title: 'Solar Flare (Warm)', value: 'forest' },
          { title: 'Void Void (Deep)', value: 'studio' },
        ]
      }
    },
    {
      name: 'sectionRadius',
      type: 'number',
      title: 'Section Circle Radius',
      initialValue: 52,
      description: 'All section statues are placed evenly on this radius.',
    },
    {
      name: 'sectionRelics',
      title: 'Section Relics (Same Controls As Links)',
      type: 'object',
      initialValue: {
        projects: { label: 'Projects', url: '#projects', color: { _type: 'color', hex: '#3b82f6' }, modelScale: 1, modelPosition: [0, 0.35, 0] },
        education: { label: 'Education', url: '#education', color: { _type: 'color', hex: '#22c55e' }, modelScale: 1, modelPosition: [0, 0.35, 0] },
        work: { label: 'Work', url: '#work', color: { _type: 'color', hex: '#ef4444' }, modelScale: 1, modelPosition: [0, 0.35, 0] },
        skills: { label: 'Skills', url: '#skills', color: { _type: 'color', hex: '#f59e0b' }, modelScale: 1, modelPosition: [0, 0.35, 0] },
        contact: { label: 'Contact', url: '#contact', color: { _type: 'color', hex: '#8b5cf6' }, modelScale: 1, modelPosition: [0, 0.35, 0] },
        about: { label: 'About', url: '#about', color: { _type: 'color', hex: '#06b6d4' }, modelScale: 1, modelPosition: [0, 0.35, 0] },
        blog: { label: 'Blog', url: '#blog', color: { _type: 'color', hex: '#f97316' }, modelScale: 1, modelPosition: [0, 0.35, 0] },
      },
      fields: [
        {
          name: 'projects',
          title: 'Projects Relic',
          type: 'object',
          fields: [
            { name: 'label', title: 'Relic Name', type: 'string', initialValue: 'Projects' },
            { name: 'url', title: 'Relic Link URL', type: 'url', initialValue: '#projects' },
            { name: 'color', title: 'Relic Base Color', type: 'color' },
            { name: 'modelScale', title: 'Relic Model Scale', type: 'number', initialValue: 1 },
            {
              name: 'modelPosition',
              title: 'Relic Model Position',
              type: 'array',
              of: [{ type: 'number' }],
              validation: (Rule: any) => Rule.length(3),
              initialValue: [0, 0.35, 0],
            },
          ],
        },
        {
          name: 'education',
          title: 'Education Relic',
          type: 'object',
          fields: [
            { name: 'label', title: 'Relic Name', type: 'string', initialValue: 'Education' },
            { name: 'url', title: 'Relic Link URL', type: 'url', initialValue: '#education' },
            { name: 'color', title: 'Relic Base Color', type: 'color' },
            { name: 'modelScale', title: 'Relic Model Scale', type: 'number', initialValue: 1 },
            {
              name: 'modelPosition',
              title: 'Relic Model Position',
              type: 'array',
              of: [{ type: 'number' }],
              validation: (Rule: any) => Rule.length(3),
              initialValue: [0, 0.35, 0],
            },
          ],
        },
        {
          name: 'work',
          title: 'Work Relic',
          type: 'object',
          fields: [
            { name: 'label', title: 'Relic Name', type: 'string', initialValue: 'Work' },
            { name: 'url', title: 'Relic Link URL', type: 'url', initialValue: '#work' },
            { name: 'color', title: 'Relic Base Color', type: 'color' },
            { name: 'modelScale', title: 'Relic Model Scale', type: 'number', initialValue: 1 },
            {
              name: 'modelPosition',
              title: 'Relic Model Position',
              type: 'array',
              of: [{ type: 'number' }],
              validation: (Rule: any) => Rule.length(3),
              initialValue: [0, 0.35, 0],
            },
          ],
        },
        {
          name: 'skills',
          title: 'Skills Relic',
          type: 'object',
          fields: [
            { name: 'label', title: 'Relic Name', type: 'string', initialValue: 'Skills' },
            { name: 'url', title: 'Relic Link URL', type: 'url', initialValue: '#skills' },
            { name: 'color', title: 'Relic Base Color', type: 'color' },
            { name: 'modelScale', title: 'Relic Model Scale', type: 'number', initialValue: 1 },
            {
              name: 'modelPosition',
              title: 'Relic Model Position',
              type: 'array',
              of: [{ type: 'number' }],
              validation: (Rule: any) => Rule.length(3),
              initialValue: [0, 0.35, 0],
            },
          ],
        },
        {
          name: 'contact',
          title: 'Contact Relic',
          type: 'object',
          fields: [
            { name: 'label', title: 'Relic Name', type: 'string', initialValue: 'Contact' },
            { name: 'url', title: 'Relic Link URL', type: 'url', initialValue: '#contact' },
            { name: 'color', title: 'Relic Base Color', type: 'color' },
            { name: 'modelScale', title: 'Relic Model Scale', type: 'number', initialValue: 1 },
            {
              name: 'modelPosition',
              title: 'Relic Model Position',
              type: 'array',
              of: [{ type: 'number' }],
              validation: (Rule: any) => Rule.length(3),
              initialValue: [0, 0.35, 0],
            },
          ],
        },
        {
          name: 'about',
          title: 'About Relic',
          type: 'object',
          fields: [
            { name: 'label', title: 'Relic Name', type: 'string', initialValue: 'About' },
            { name: 'url', title: 'Relic Link URL', type: 'url', initialValue: '#about' },
            { name: 'color', title: 'Relic Base Color', type: 'color' },
            { name: 'modelScale', title: 'Relic Model Scale', type: 'number', initialValue: 1 },
            {
              name: 'modelPosition',
              title: 'Relic Model Position',
              type: 'array',
              of: [{ type: 'number' }],
              validation: (Rule: any) => Rule.length(3),
              initialValue: [0, 0.35, 0],
            },
          ],
        },
        {
          name: 'blog',
          title: 'Blog Relic',
          type: 'object',
          fields: [
            { name: 'label', title: 'Relic Name', type: 'string', initialValue: 'Blog' },
            { name: 'url', title: 'Relic Link URL', type: 'url', initialValue: '#blog' },
            { name: 'color', title: 'Relic Base Color', type: 'color' },
            { name: 'modelScale', title: 'Relic Model Scale', type: 'number', initialValue: 1 },
            {
              name: 'modelPosition',
              title: 'Relic Model Position',
              type: 'array',
              of: [{ type: 'number' }],
              validation: (Rule: any) => Rule.length(3),
              initialValue: [0, 0.35, 0],
            },
          ],
        },
      ],
      description: 'Fixed per-section relic settings using the same control style as Link Relics.',
    },
    {
      name: 'sceneModels',
      title: 'Custom Scene Models (Unlimited)',
      type: 'array',
      description: 'Place any number of 3D models anywhere in the scene with transform, animation, auto-rotation, and glow ring controls.',
      of: [
        {
          type: 'object',
          fields: [
            { name: 'name', title: 'Model Name', type: 'string' },
            {
              name: 'modelFile',
              title: 'Model File (GLB upload)',
              type: 'file',
              options: {
                accept: '.glb,model/gltf-binary',
              },
              description: 'Upload a GLB directly from your machine. If both file and URL are set, uploaded file is used.',
            },
            { name: 'modelUrl', title: 'Model URL / Reference', type: 'url' },
            {
              name: 'position',
              title: 'Position [x, y, z]',
              type: 'array',
              of: [{ type: 'number' }],
              validation: (Rule: any) => Rule.length(3),
              initialValue: [0, 0, 0],
            },
            {
              name: 'rotation',
              title: 'Rotation [x, y, z]',
              type: 'array',
              of: [{ type: 'number' }],
              validation: (Rule: any) => Rule.length(3),
              initialValue: [0, 0, 0],
            },
            {
              name: 'scale',
              title: 'Scale',
              type: 'number',
              initialValue: 1,
            },
            {
              name: 'playAnimation',
              title: 'Play Embedded Animation Clip',
              type: 'boolean',
              initialValue: true,
            },
            {
              name: 'animationClip',
              title: 'Animation Clip',
              type: 'string',
              components: { input: AnimationClipSelectInput as any },
              description: 'Select from detected clips in the uploaded/model URL GLB.',
            },
            {
              name: 'doubleSidedMaterials',
              title: 'Double-Sided Materials',
              type: 'boolean',
              initialValue: true,
              description: 'Fixes models that render incorrectly from certain angles due to face culling.',
            },
            {
              name: 'allowTransparency',
              title: 'Allow Transparency',
              type: 'boolean',
              initialValue: false,
              description: 'Use transparent material rendering for this model. Keep OFF to force opaque rendering for stability.',
            },
            {
              name: 'autoRotate',
              title: 'Auto-Rotate',
              type: 'boolean',
              initialValue: false,
            },
            {
              name: 'autoRotateSpeedX',
              title: 'Auto-Rotate Speed X',
              type: 'number',
              initialValue: 0,
            },
            {
              name: 'autoRotateSpeedY',
              title: 'Auto-Rotate Speed Y',
              type: 'number',
              initialValue: 0.4,
            },
            {
              name: 'autoRotateSpeedZ',
              title: 'Auto-Rotate Speed Z',
              type: 'number',
              initialValue: 0,
            },
            {
              name: 'glowRing',
              title: 'Enable Glow Ring',
              type: 'boolean',
              initialValue: false,
            },
            {
              name: 'glowRingColor',
              title: 'Glow Ring Color',
              type: 'color',
            },
            {
              name: 'glowRingIntensity',
              title: 'Glow Ring Intensity',
              type: 'number',
              initialValue: 2,
            },
          ],
          preview: {
            select: {
              title: 'name',
              subtitle: 'modelUrl',
            },
            prepare({ title, subtitle }: any) {
              return {
                title: title || 'Scene Model',
                subtitle: subtitle || 'No model URL',
              }
            },
          },
        },
      ],
    },
    {
      name: 'linkRelics',
      title: 'Link Relics (Editable Properties)',
      type: 'object',
      initialValue: {
        github: { label: 'GitHub', url: 'https://github.com', color: { _type: 'color', hex: '#f8fafc' }, modelScale: 1.2, modelPosition: [0, 0.05, 0] },
        linkedin: { label: 'LinkedIn', url: 'https://linkedin.com', color: { _type: 'color', hex: '#0ea5e9' }, modelScale: 1.2, modelPosition: [0, 0.05, 0] },
        resume: { label: 'Resume', url: '/resume', color: { _type: 'color', hex: '#ef4444' }, modelScale: 1.2, modelPosition: [0, 0.05, 0] },
      },
      fields: [
        {
          name: 'github',
          title: 'GitHub Relic',
          type: 'object',
          fields: [
            { name: 'label', title: 'Relic Name', type: 'string', initialValue: 'GitHub' },
            { name: 'url', title: 'Relic Link URL', type: 'url', initialValue: 'https://github.com' },
            { name: 'color', title: 'Relic Base Color', type: 'color' },
            { name: 'modelScale', title: 'Relic Model Scale', type: 'number', initialValue: 1.2 },
            {
              name: 'modelPosition',
              title: 'Relic Model Position',
              type: 'array',
              of: [{ type: 'number' }],
              validation: (Rule: any) => Rule.length(3),
              initialValue: [0, 0.05, 0],
            },
          ],
        },
        {
          name: 'linkedin',
          title: 'LinkedIn Relic',
          type: 'object',
          fields: [
            { name: 'label', title: 'Relic Name', type: 'string', initialValue: 'LinkedIn' },
            { name: 'url', title: 'Relic Link URL', type: 'url', initialValue: 'https://linkedin.com' },
            { name: 'color', title: 'Relic Base Color', type: 'color' },
            { name: 'modelScale', title: 'Relic Model Scale', type: 'number', initialValue: 1.2 },
            {
              name: 'modelPosition',
              title: 'Relic Model Position',
              type: 'array',
              of: [{ type: 'number' }],
              validation: (Rule: any) => Rule.length(3),
              initialValue: [0, 0.05, 0],
            },
          ],
        },
        {
          name: 'resume',
          title: 'Resume Relic',
          type: 'object',
          fields: [
            { name: 'label', title: 'Relic Name', type: 'string', initialValue: 'Resume' },
            { name: 'url', title: 'Relic Link URL', type: 'url', initialValue: '/resume' },
            { name: 'color', title: 'Relic Base Color', type: 'color' },
            { name: 'modelScale', title: 'Relic Model Scale', type: 'number', initialValue: 1.2 },
            {
              name: 'modelPosition',
              title: 'Relic Model Position',
              type: 'array',
              of: [{ type: 'number' }],
              validation: (Rule: any) => Rule.length(3),
              initialValue: [0, 0.05, 0],
            },
          ],
        },
      ],
      description: 'Edits name, URL, base color, and scale for fixed hard-coded link relics.',
    },
  ]
}
